### ISSUE TITLE
Speech Api - Jetty ALPN/NPN has not been properly configured.

### ISSUE THREAD

**Issue by naushad97** [GoogleCloudPlatform/java-docs-samples#766]
I am getting the below exception when running the sample "speech" application as a plain java application. I have not run it on any server as of now.

Sample application can be found at- https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/speech/cloud-client.

Exception in thread "main" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:174)
at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:151)
at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:139)
at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:109)
at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.(NettyChannelBuilder.java:470)
at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:338)
at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:305)
at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:139)
at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116)
at com.google.api.gax.grpc.ChannelAndExecutor.create(ChannelAndExecutor.java:65)
at com.google.api.gax.grpc.ClientSettings.getChannelAndExecutor(ClientSettings.java:91)
at com.google.cloud.speech.v1.SpeechClient.(SpeechClient.java:140)
at com.google.cloud.speech.v1.SpeechClient.create(SpeechClient.java:131)
at com.google.cloud.speech.v1.SpeechClient.create(SpeechClient.java:123)
at com.example.speech.QuickstartSample.main(QuickstartSample.java:38)

I have tried most of the steps provided over the net but no luck. It uses google cloud speech version - 0.20.3-alpha. I have also tried with google cloud speech version -0.17.1-alpha but same issue.

**Comment by lesv** [comment]
Where are you using this?  Tomcat perhaps - there is a known bug that should be fixed shortly.

**Comment by naushad97** [comment]
I have not used in any container or server. I have only runt it as a normal Java Application. Through maven I have run the example application as - 
mvn exec:java -Dexec.mainClass=com.example.speech.QuickstartSample
I have also run it from eclipse as - > Run as Java Application. Same issue is occurring.
Issue is consistent across the system on windows 7 and windows 10.

**Comment by mamtaT** [comment]
You should try adding io/netty/netty-tcnative-boringssl-static/2.0.3.Final/netty-tcnative-boringssl-static-2.0.3.Final.jar to your classpath.

**Comment by naushad97** [comment]
@mamtaT I tried by adding netty-tcnative-boringssl-static-2.0.3.Final.jar in classpath but still the same issue.

FYI - below is dependency tree-

[INFO] com.example.speech:speech-google-cloud-samples:jar:1.0.0
[INFO] +- com.google.cloud:google-cloud:jar:0.21.0-alpha:compile
[INFO] |  +- com.google.cloud:google-cloud-bigquery:jar:0.21.0-beta:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core-http:jar:1.3.0:compile
[INFO] |  |  |  +- com.google.auth:google-auth-library-credentials:jar:0.7.0:compile
[INFO] |  |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.7.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client:jar:1.22.0:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  |  |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  |  |  +- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |  |  |  +- com.google.api-client:google-api-client:jar:1.22.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client-appengine:jar:1.22.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client-jackson:jar:1.22.0:compile
[INFO] |  |  |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.22.0:compile
[INFO] |  |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  |  \- com.google.apis:google-api-services-bigquery:jar:v2-rev347-1.22.0:compile
[INFO] |  +- com.google.cloud:google-cloud-compute:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.apis:google-api-services-compute:jar:v1-rev103-1.21.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.3.0:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  |  +- org.json:json:jar:20160810:compile
[INFO] |  |  +- com.google.api:api-common:jar:1.1.0:compile
[INFO] |  |  +- com.google.api:gax:jar:1.5.0:compile
[INFO] |  |  |  +- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] |  |  |  \- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.3.1:compile
[INFO] |  |  |  +- com.google.protobuf:protobuf-java:jar:3.3.1:compile
[INFO] |  |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-datastore:jar:1.3.0:compile
[INFO] |  |  +- com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0:compile
[INFO] |  |  +- com.google.cloud.datastore:datastore-v1-proto-client:jar:1.3.0:compile
[INFO] |  |  |  \- com.google.http-client:google-http-client-protobuf:jar:1.20.0:compile
[INFO] |  |  \- com.google.api.grpc:grpc-google-common-protos:jar:0.1.14:compile
[INFO] |  |     \- io.grpc:grpc-protobuf:jar:1.4.0:compile
[INFO] |  |        \- io.grpc:grpc-protobuf-lite:jar:1.4.0:compile
[INFO] |  +- com.google.cloud:google-cloud-dns:jar:0.21.0-alpha:compile
[INFO] |  |  +- com.google.apis:google-api-services-dns:jar:v1-rev7-1.21.0:compile
[INFO] |  |  \- commons-fileupload:commons-fileupload:jar:1.3.2:compile
[INFO] |  |     \- commons-io:commons-io:jar:2.2:compile
[INFO] |  +- com.google.cloud:google-cloud-errorreporting:jar:0.21.0-alpha:compile
[INFO] |  |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core-grpc:jar:1.3.0:compile
[INFO] |  |  |  \- io.grpc:grpc-context:jar:1.4.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-error-reporting-v1beta1:jar:0.1.14:compile
[INFO] |  |  +- io.grpc:grpc-netty:jar:1.4.0:compile
[INFO] |  |  |  +- io.grpc:grpc-core:jar:1.4.0:compile (version selected from constraint [1.4.0,1.4.0])
[INFO] |  |  |  |  \- com.google.instrumentation:instrumentation-api:jar:0.4.2:compile
[INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.11.Final:compile (version selected from constraint [4.
[INFO] |  |  |  |  +- io.netty:netty-codec-http:jar:4.1.11.Final:compile
[INFO] |  |  |  |  |  \- io.netty:netty-codec:jar:4.1.11.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-handler:jar:4.1.11.Final:compile
[INFO] |  |  |  |     \- io.netty:netty-buffer:jar:4.1.11.Final:compile
[INFO] |  |  |  |        \- io.netty:netty-common:jar:4.1.11.Final:compile
[INFO] |  |  |  \- io.netty:netty-handler-proxy:jar:4.1.11.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport:jar:4.1.11.Final:compile
[INFO] |  |  |     |  \- io.netty:netty-resolver:jar:4.1.11.Final:compile
[INFO] |  |  |     \- io.netty:netty-codec-socks:jar:4.1.11.Final:compile
[INFO] |  |  +- io.grpc:grpc-stub:jar:1.4.0:compile
[INFO] |  |  \- io.grpc:grpc-auth:jar:1.4.0:compile
[INFO] |  +- com.google.cloud:google-cloud-language:jar:0.21.0-beta:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-language-v1:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-language-v1beta2:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-logging:jar:1.3.0:compile
[INFO] |  |  +- com.google.api:gax-grpc:jar:0.22.0:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-logging-v2:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-monitoring:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-monitoring-v3:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-pubsub:jar:0.21.0-beta:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-resourcemanager:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.apis:google-api-services-cloudresourcemanager:jar:v1beta1-rev10-1.21.0:compile
[INFO] |  +- com.google.cloud:google-cloud-speech:jar:0.21.0-alpha:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-speech-v1beta1:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-speech-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-storage:jar:1.3.0:compile
[INFO] |  |  \- com.google.apis:google-api-services-storage:jar:v1-rev108-1.22.0:compile
[INFO] |  +- com.google.cloud:google-cloud-trace:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-trace-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-translate:jar:1.3.0:compile
[INFO] |  |  \- com.google.apis:google-api-services-translate:jar:v2-rev47-1.22.0:compile
[INFO] |  +- com.google.cloud:google-cloud-vision:jar:0.21.0-beta:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-vision-v1:jar:0.1.14:compile
[INFO] |  \- com.google.cloud:google-cloud-spanner:jar:0.21.0-beta:compile
[INFO] |     +- com.google.api.grpc:proto-google-cloud-spanner-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-cloud-spanner-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-longrunning-v1:jar:0.1.14:compile
[INFO] |     |  \- com.google.api.grpc:proto-google-longrunning-v1:jar:0.1.14:compile
[INFO] |     \- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- com.google.truth:truth:jar:0.34:test
[INFO]    +- com.google.guava:guava:jar:20.0:compile
[INFO]    \- com.google.errorprone:error_prone_annotations:jar:2.0.18:compile
[INFO] ------------------------------------------------------------------------

**Comment by naushad97** [comment]
I also added alpn-boot-7.1.0.v20141016.jar (as I am executing on jdk1.7.0_51, OS- Windows 7) in Bootstrap entries (described [here](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#openssl-statically-linked-netty-tcnative-boringssl-static)) and run the application from Eclipse IDE- It is throwing the below error  #-
```
io.grpc.Context: Storage override doesn't exist. Using default.
java.lang.ClassNotFoundException: io.grpc.override.ContextStorageOverride
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:190)
	at io.grpc.Context.<clinit>(Context.java:132)
	at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:108)
	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:554)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor.interceptCall(GrpcHeaderInterceptor.java:57)
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:119)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:533)
	at com.google.api.gax.grpc.GrpcDirectCallable.newCall(GrpcDirectCallable.java:67)
	at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:61)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:65)
	at com.google.api.gax.grpc.GrpcAttemptCallable.call(GrpcAttemptCallable.java:80)
	at com.google.api.gax.grpc.GrpcRetryingCallable.futureCall(GrpcRetryingCallable.java:64)
	at com.google.api.gax.grpc.GrpcRetryingCallable.futureCall(GrpcRetryingCallable.java:46)
	at com.google.api.gax.rpc.EntryPointUnaryCallable.futureCall(EntryPointUnaryCallable.java:70)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:89)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:114)
	at com.google.cloud.speech.v1.SpeechClient.recognize(SpeechClient.java:225)
	at com.google.cloud.speech.v1.SpeechClient.recognize(SpeechClient.java:189)
	at com.example.speech.QuickstartSample.main(QuickstartSample.java:62)
Exception in thread "main" com.google.api.gax.grpc.GrpcApiException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:112)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:53)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:466)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED
	at io.grpc.Status.asRuntimeException(Status.java:543)
	... 15 more
```
```
Dependency Tree - >

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ speech-google-cloud-samples ---
[INFO] com.example.speech:speech-google-cloud-samples:jar:1.0.0
[INFO] +- com.google.cloud:google-cloud:jar:0.21.0-alpha:compile
[INFO] |  +- com.google.cloud:google-cloud-bigquery:jar:0.21.0-beta:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core-http:jar:1.3.0:compile
[INFO] |  |  |  +- com.google.auth:google-auth-library-credentials:jar:0.7.0:compile
[INFO] |  |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:0.7.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client:jar:1.22.0:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |  |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |  |  |  |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |  |  |  |     \- commons-codec:commons-codec:jar:1.3:compile
[INFO] |  |  |  +- com.google.oauth-client:google-oauth-client:jar:1.22.0:compile
[INFO] |  |  |  +- com.google.api-client:google-api-client:jar:1.22.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client-appengine:jar:1.22.0:compile
[INFO] |  |  |  +- com.google.http-client:google-http-client-jackson:jar:1.22.0:compile
[INFO] |  |  |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.22.0:compile
[INFO] |  |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.1.3:compile
[INFO] |  |  \- com.google.apis:google-api-services-bigquery:jar:v2-rev347-1.22.0:compile
[INFO] |  +- com.google.cloud:google-cloud-compute:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.apis:google-api-services-compute:jar:v1-rev103-1.21.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core:jar:1.3.0:compile
[INFO] |  |  +- joda-time:joda-time:jar:2.9.2:compile
[INFO] |  |  +- org.json:json:jar:20160810:compile
[INFO] |  |  +- com.google.api:api-common:jar:1.1.0:compile
[INFO] |  |  +- com.google.api:gax:jar:1.5.0:compile
[INFO] |  |  |  +- com.google.auto.value:auto-value:jar:1.2:compile
[INFO] |  |  |  \- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java-util:jar:3.3.1:compile
[INFO] |  |  |  +- com.google.protobuf:protobuf-java:jar:3.3.1:compile
[INFO] |  |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-datastore:jar:1.3.0:compile
[INFO] |  |  +- com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0:compile
[INFO] |  |  +- com.google.cloud.datastore:datastore-v1-proto-client:jar:1.3.0:compile
[INFO] |  |  |  \- com.google.http-client:google-http-client-protobuf:jar:1.20.0:compile
[INFO] |  |  \- com.google.api.grpc:grpc-google-common-protos:jar:0.1.14:compile
[INFO] |  |     \- io.grpc:grpc-protobuf:jar:1.4.0:compile
[INFO] |  |        \- io.grpc:grpc-protobuf-lite:jar:1.4.0:compile
[INFO] |  +- com.google.cloud:google-cloud-dns:jar:0.21.0-alpha:compile
[INFO] |  |  +- com.google.apis:google-api-services-dns:jar:v1-rev7-1.21.0:compile
[INFO] |  |  \- commons-fileupload:commons-fileupload:jar:1.3.2:compile
[INFO] |  |     \- commons-io:commons-io:jar:2.2:compile
[INFO] |  +- com.google.cloud:google-cloud-errorreporting:jar:0.21.0-alpha:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core-grpc:jar:1.3.0:compile
[INFO] |  |  |  \- io.grpc:grpc-context:jar:1.4.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-error-reporting-v1beta1:jar:0.1.14:compile
[INFO] |  |  +- io.grpc:grpc-netty:jar:1.4.0:compile
[INFO] |  |  |  +- io.grpc:grpc-core:jar:1.4.0:compile (version selected from constraint [1.4.0,1.4.0])
[INFO] |  |  |  |  \- com.google.instrumentation:instrumentation-api:jar:0.4.2:compile
[INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.11.Final:compile (version selected from constraint [4.1.11.Final,4.1.11.Final])
[INFO] |  |  |  |  +- io.netty:netty-codec-http:jar:4.1.11.Final:compile
[INFO] |  |  |  |  |  \- io.netty:netty-codec:jar:4.1.11.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-handler:jar:4.1.11.Final:compile
[INFO] |  |  |  |     \- io.netty:netty-buffer:jar:4.1.11.Final:compile
[INFO] |  |  |  |        \- io.netty:netty-common:jar:4.1.11.Final:compile
[INFO] |  |  |  \- io.netty:netty-handler-proxy:jar:4.1.11.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport:jar:4.1.11.Final:compile
[INFO] |  |  |     |  \- io.netty:netty-resolver:jar:4.1.11.Final:compile
[INFO] |  |  |     \- io.netty:netty-codec-socks:jar:4.1.11.Final:compile
[INFO] |  |  +- io.grpc:grpc-stub:jar:1.4.0:compile
[INFO] |  |  \- io.grpc:grpc-auth:jar:1.4.0:compile
[INFO] |  +- com.google.cloud:google-cloud-language:jar:0.21.0-beta:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-language-v1:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-language-v1beta2:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-logging:jar:1.3.0:compile
[INFO] |  |  +- com.google.api:gax-grpc:jar:0.22.0:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-logging-v2:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-monitoring:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-monitoring-v3:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-pubsub:jar:0.21.0-beta:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-resourcemanager:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.apis:google-api-services-cloudresourcemanager:jar:v1beta1-rev10-1.21.0:compile
[INFO] |  +- com.google.cloud:google-cloud-speech:jar:0.21.0-alpha:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-speech-v1beta1:jar:0.1.14:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-speech-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-storage:jar:1.3.0:compile
[INFO] |  |  \- com.google.apis:google-api-services-storage:jar:v1-rev108-1.22.0:compile
[INFO] |  +- com.google.cloud:google-cloud-trace:jar:0.21.0-alpha:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-trace-v1:jar:0.1.14:compile
[INFO] |  +- com.google.cloud:google-cloud-translate:jar:1.3.0:compile
[INFO] |  |  \- com.google.apis:google-api-services-translate:jar:v2-rev47-1.22.0:compile
[INFO] |  +- com.google.cloud:google-cloud-vision:jar:0.21.0-beta:compile
[INFO] |  |  \- com.google.api.grpc:proto-google-cloud-vision-v1:jar:0.1.14:compile
[INFO] |  \- com.google.cloud:google-cloud-spanner:jar:0.21.0-beta:compile
[INFO] |     +- com.google.api.grpc:proto-google-cloud-spanner-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-cloud-spanner-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1:jar:0.1.14:compile
[INFO] |     +- com.google.api.grpc:grpc-google-longrunning-v1:jar:0.1.14:compile
[INFO] |     |  \- com.google.api.grpc:proto-google-longrunning-v1:jar:0.1.14:compile
[INFO] |     \- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] +- io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- com.google.truth:truth:jar:0.34:test
[INFO]    +- com.google.guava:guava:jar:20.0:compile
[INFO]    \- com.google.errorprone:error_prone_annotations:jar:2.0.18:compile
```

Java Class - >

```
package com.example.speech;

// [START speech_quickstart]
// Imports the Google Cloud client library
import com.google.cloud.speech.v1.RecognitionAudio;
import com.google.cloud.speech.v1.RecognitionConfig;
import com.google.cloud.speech.v1.RecognitionConfig.AudioEncoding;
import com.google.cloud.speech.v1.RecognizeResponse;
import com.google.cloud.speech.v1.SpeechClient;
import com.google.cloud.speech.v1.SpeechRecognitionAlternative;
import com.google.cloud.speech.v1.SpeechRecognitionResult;
import com.google.protobuf.ByteString;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class QuickstartSample {
  public static void main(String... args) throws Exception {
	 Logger.getLogger("").setLevel(Level.FINE);
    // Instantiates a client
    SpeechClient speech = SpeechClient.create();

    // The path to the audio file to transcribe
    String fileName = "./resources/audio.raw";

    // Reads the audio file into memory
    Path path = Paths.get(fileName);
    byte[] data = Files.readAllBytes(path);
    ByteString audioBytes = ByteString.copyFrom(data);

    // Builds the sync recognize request
    RecognitionConfig config = RecognitionConfig.newBuilder()
        .setEncoding(AudioEncoding.LINEAR16)
        .setSampleRateHertz(16000)
        .setLanguageCode("en-US")
        .build();
    RecognitionAudio audio = RecognitionAudio.newBuilder()
        .setContent(audioBytes)
        .build();

    // Performs speech recognition on the audio file
    RecognizeResponse response = speech.recognize(config, audio);
    List<SpeechRecognitionResult> results = response.getResultsList();

    for (SpeechRecognitionResult result: results) {
      List<SpeechRecognitionAlternative> alternatives = result.getAlternativesList();
      for (SpeechRecognitionAlternative alternative: alternatives) {
        System.out.printf("Transcription: %s%n", alternative.getTranscript());
      }
    }
    speech.close();
  }
}
// [END speech_quickstart]

```
Without alpn-boot-7.1.0.v20141016.jar, it is always throwing the error - `Jetty ALPN/NPN has not been properly configured.`

**Comment by lesv** [comment]
My guess is that it's attempting to write to some directory (probably 'tmp') and can't do so.  You picked the correct [version](https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-versions) of alpnboot, so that looks good.  Though you really shouldn't have needed it as you already have the correct version of BoringSSL twice. (and it does run on Windows).

I suspect upgrading to the .1 of the cloud libraries won't help much, but it would be nice if you'd try.

Have you done a `gcloud init` and `gcloud auth application-default login` ??  (I would expect a different error message if you haven't, but I want to check).

Lastly, I wonder if perhaps the path's need to be changed to be Windows paths.  I'm beginning to suspect that this hasn't been tested on Windows. @gguuss PTAL
(but again, I'd expect a different error message)

[Netty Instructions](http://netty.io/wiki/forked-tomcat-native.html) might be worth looking at. [source](https://github.com/netty/netty-tcnative).

I'm trying to find the code that hooks up BoringSSL on Windows, but haven't yet found it, will update if I find it.

**Comment by lesv** [comment]
So, my understanding is that netty-tcnative-borringSSL (aka `netty-tcnative-windows-x86_64 .dll`) getting unpacked to a system temp directory.  What it's looking like is that your JVM isn't able to write to it for some reason.

**Comment by lesv** [comment]
Engineering suggested that you might wish to manually unpack the jar.

See https://github.com/netty/netty/blob/64a3e6c69c1ba49ccd7fe0410e6b2131cda9315c/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L419

Just unpack the os/arch-specific library anywhere and rename it to just "netty-tcnative.dll". Then configure LIBPATH.

**Comment by naushad97** [comment]
@lesv Thanks for your response. I will try and let you know.

**Comment by naushad97** [comment]
I unpacked windows specific library and renamed to "netty-tcnative.dll". Then I configured LIBPATH in windows environment variables and set the value to "netty-tcnative.dll".

Then I run the application in the following way -

1. **With** alpn-boot-7.1.0.v20141016.jar in bootstrap entries-
      Then it throws the below error (full stack-trace already provided earlier)- 
      `
io.grpc.Context: Storage override doesn't exist. Using default.
      java.lang.ClassNotFoundException: io.grpc.override.ContextStorageOverride
     ........
`

2. **Without** alpn-boot-7.1.0.v20141016.jar in bootstrap entries-
      It throws the below error (full stack-trace already provided earlier)-
      `Exception in thread "main" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:174)
.................
        `

Is it the correct approach?


P.S. 
      I have set "GOOGLE_APPLICATION_CREDENTIALS" in environment variable to the path of service 
       account key(json file).
       I am running the application on latest version of google cloud api-

     <dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud</artifactId>
			<version>0.21.0-alpha</version>
		</dependency>

**Comment by lesv** [comment]
`<version>0.21.1-alpha</version>` is current, so you might try it.

Doesn't sound like things worked at all, since the second option is what should work.

I'm a fan of setting using `gcloud init` & `gcloud auth application-default login` as it makes a few things easier.  When you use a service account and `GOOGLE_APPLICATION_CREDENTIALS` you need to make sure you give the account the right IAM privileges.  Note the environment variable takes precedence over the gcloud configurations.

Recommendation - try option 2 using the updated library - they wouldn't have done a .1 release unless there was something wrong with the .0

**Comment by naushad97** [comment]
I tried with the latest version `<version>0.21.1-alpha</version>` but the same problem. I also set the `gcloud init` & `gcloud auth application-default login` after removing `GOOGLE_APPLICATION_CREDENTIALS` but still the same problem.

**Comment by naushad97** [comment]
I tried to check OpenSSL and Alpn availability and always showing unavailable though these are present in classpath -

```
                System.out.println("Is OpenSSL available? " + OpenSsl.isAvailable());
		System.out.println("Is ALPN available?    " + OpenSsl.isAlpnSupported());

		if (OpenSsl.unavailabilityCause() != null) {
			System.out.println("Unavailability cause:");
			OpenSsl.unavailabilityCause().printStackTrace(System.out); 
			return;
		}
```
It prints the following - 

```
Is OpenSSL available? false
Is ALPN available?    false
Unavailability cause:
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-windows-x86_32, netty-tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:178)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:403)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:85)
	at com.example.speech.QuickstartSample.main(QuickstartSample.java:50)

```

**Comment by lesv** [comment]
Take a look at this [comment](https://github.com/GoogleCloudPlatform/java-docs-samples/issues/766#issuecomment-320028056).  Try unpacking (unzip) the TCNative-boringssl-static jar and installing the dll somewhere then add it to your LIBPATH envVar. 

Some reason the directory isn't writable.

**Comment by naushad97** [comment]
I added netty-tcnative.dll and still it is unresolved.

**Comment by lesv** [comment]
This has gone on long enough. I'll try to get access to a windows 10 machine tomorrow and I'll try to make it work.

**Comment by garrettjonesgoogle** [comment]
@naushad97 I noticed that you are trying to load netty-tcnative-windows-x86_32 (i.e. 32-bit). 32-bit is not supported; you need to make sure you are running 64-bit Java on 64-bit Windows.

**Comment by mirkorodriguez** [comment]
Guys ... not sure if this has been fixed, but a workaround that worked to me was to add a Jetty jar as javaagent to  the JVM:

```
javac -cp ".:lib/*" Test.java
java -javaagent:/<some path>/jetty-alpn-agent-2.0.6.jar -cp ".:lib/*" Test
```

In case of Web Application Servers, you can add the javaagent by using a similar approach here https://docs.newrelic.com/docs/agents/java-agent/installation/include-java-agent-jvm-argument
